[package]
name = "etesync"
version = "0.1.0"
authors = ["Tom Hacohen <tom@stosb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
openssl = "~0.10.28"
base64 = "~0.12.0"
hmac = "~0.7.1"
sha2 = "~0.8.1"
