[package]
name = "etesync"
version = "0.1.0"
authors = ["Tom Hacohen <tom@stosb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[build-dependencies]
cbindgen = "^0.13.2"

[dependencies]
openssl = "^0.10.28"
base64 = "^0.12.0"
hmac = "^0.7.1"
sha2 = "^0.8.1"
http = "^0.2.0"
url = "^2.1.1"
hex = "^0.4.2"
serde = { version = "^1.0.105", features = ["derive"] }
serde_json = "^1.0.48"
reqwest = { version = "^0.10.4", features = ["blocking", "json"] }
